services:
  run:
    image: exercise-10 # Tên image đã build
    container_name: ex10_gx_run
    command: python main.py
    volumes:
      # Mount thư mục hiện tại (Exercise-10) vào /app
      - .:/app
      # Mount thư mục data chứa file csv
      - ./data:/app/data:ro # Chỉ cần đọc
      # Mount thư mục great_expectations để lưu cấu hình và kết quả GX (tùy chọn)
      # Nếu không mount, nó sẽ tạo trong container và mất khi container bị xóa
      - ./great_expectations:/app/great_expectations:rw
    working_dir: /app
